name = "spin-grannycasino-co-at"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-grannycasino.co.at"
HMAC_KEY = "2966ccdc57dc7533859d6e04a75e6c8e0226b2afd84582c9b66238ad98aac418"
COOKIE_NAME = "y9g"
PLAY_PATH = "try"
BUTTON_ID = "p5cc421844b48636e21f8f96f115747f5"
GATE_SALT = "871dd34b62f48aec"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "o8vp"
CTA_SELECTOR = ".play-button"
